Add functionality to see favorite gem files
Shpigford/gemfile.directory pull request #19
Opened 2024-01-18 14:08 UTC by varkum

Closes #17 

Gemfiles that have been starred show up under the profile dropdown as "Favorite Gemfiles." Made some UI changes here to the sign out button — can change these if needed.

<img width="1710" alt="Screenshot 2024-01-18 at 9 08 15 AM" src="https://github.com/Shpigford/gemfile.directory/assets/57076268/539a19e2-112c-486e-8785-10b04d4ea607">

<img width="1710" alt="Screenshot 2024-01-18 at 9 08 28 AM" src="https://github.com/Shpigford/gemfile.directory/assets/57076268/81aa99b3-159e-4a4f-a6c4-71b8b15617cc">

2024-01-19 20:07 UTC, robzolkos requested changes

2024-01-19 20:07 UTC, robzolkos commented on config/routes.rb
> +  get "my/favorite-gemfiles", to: "my#favorite_gemfiles"
Would prefer to keep RESTful routing with the standard actions.  Although love the namespacing.  
```suggestion
  namespace :my do 
    resources :favorites, only: [:index]
  end
```

2024-01-19 20:07 UTC, robzolkos commented on app/views/my/favorite_gemfiles.html.erb
> +	    <%= render "gemfiles/gemfile_list_item", gemfile: gemfile %>
You can use a collection partial here.
```suggestion
	    <%= render partial: "gemfiles/gemfile_list_item", collection: @favourite_gemfiles %>
```

2024-01-19 20:07 UTC, robzolkos commented on app/views/my/favorite_gemfiles.html.erb
> +	<span class="italic text-sm text-gray-500">You don't have any favorite gemfiles yet.</span>
Instead of checking if there are any favourites present you can just render this span if there are no list items rendered.
```suggestion
	<span class="italic text-sm text-gray-500 hidden only:inline-block">You don't have any favorite gemfiles yet.</span>
```

2024-01-19 20:07 UTC, robzolkos commented on dump.rdb
Do we need this file in the PR?

2024-01-20 14:36 UTC, varkum commented on app/views/my/favorite_gemfiles.html.erb
> +	    <%= render "gemfiles/gemfile_list_item", gemfile: gemfile %>
I've updated `gemfiles/index.html.erb` too where it used the same iteration.

2024-01-20 14:36 UTC, varkum commented on app/views/my/favorite_gemfiles.html.erb
> +	<span class="italic text-sm text-gray-500">You don't have any favorite gemfiles yet.</span>
That's neat didn't know you could do that

2024-01-20 23:33 UTC, robzolkos approved these changes
Thanks @varkum !  Looks good.

2024-01-20 23:48 UTC, merged